// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odrgbiodqrmetmodxfjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcmdiaW9kcXJtZXRtb2R4ZmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY4Njk0MjMsImV4cCI6MjA1MjQ0NTQyM30.sTC6fP2sgC_rcsybzmiYxVzu_P8gaufwvXTAQay4QEA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);